//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baker.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chek
    {
        public int Id { get; set; }
        public Nullable<int> Id_goods { get; set; }
        public Nullable<int> Id_Cashier { get; set; }
        public Nullable<int> Kol_vo { get; set; }
        public Nullable<double> Summa { get; set; }
        public Nullable<System.DateTime> Data_sale { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Cashier Cashier { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
