//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baker.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BakerEntities1 : DbContext
    {
        public BakerEntities1()
            : base("name=BakerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cashier> Cashier { get; set; }
        public virtual DbSet<Chek> Chek { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
